backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img"
public_folder: "img"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: 'Publish Date', name: 'date', widget: 'datetime', dateFormat: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: Author, name: author, widget: hidden, default: Andrew Escay}
      - {label: Author Image, name: authorImage, widget: hidden, default: "img/headshot.jpeg"}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: 'Blog post content', name: 'body', widget: 'markdown'}